# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development CI

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: [self-hosted, development]
    strategy:
      matrix:
        node-version: [16.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: if [ -d "dir_path" ]; then cp -r dir dir; fi
      - run: if [ -d "dir" ]; then rm -r dir; fi
      - run: npm i
      - run: cp -r dir dir
      - run: cp -r dir dir
      - run: rm -r dir
      - run: if [ -d "dir" ]; then cp -r dir dir; fi
      - run: if [ -d "dir" ]; then rm -r dir; fi
      - run: cd dir
